### ISSUE TITLE
Add Google Android App Analytics

### ISSUE THREAD

**Issue by chris-piekarski** [chris-piekarski/android-fourteeners#13]
https://developers.google.com/analytics/devguides/collection/android/v4/?configured

**Comment by johncbahr** [comment]
Is there some other change that needs to be committed for this?  After I merged I'm getting a strange error in a generated xml file: 
/Users/johncbahr/Documents/workspace/android-fourteeners/app/build/generated/res/google-services/debug/values/values.xml
Error:(3, 44) Error: Attribute name "UA" associated with an element type "enter" must be followed by the ' = ' character.
:app:mergeDebugResources FAILED
Error:Execution failed for task ':app:mergeDebugResources'.

> /Users/johncbahr/Documents/workspace/android-fourteeners/app/build/generated/res/google-services/debug/values/values.xml:3:44: Error: Attribute name "UA" associated with an element type "enter" must be followed by the ' = ' character.

**Comment by johncbahr** [comment]
Do you have JDK 1.8 installed?

**Comment by chris-piekarski** [comment]
Sorry John, just saw these comments.
